apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-incident-board
  labels:
    app: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            until nc -z postgresql 5432;
            do echo "waiting for db"; sleep 2;
            done

      containers:
      - name: api
        image: image-registry.openshift-image-registry.svc:5000/devops-incident-board/api:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgresql:5432/incidentboard
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: incident-board-secrets
              key: DB_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SERVER_PORT
          value: "8080"

        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: devops-incident-board
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080


